# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
variable "use_cli" {
  description = "在本地開發時使用 Azure CLI 登入"
  type        = bool
  default     = true
}

variable "use_msi" {
  description = "在遠端執行時使用受控身分識別登入"
  type        = bool
  default     = false
}
